### ISSUE TITLE
Changing to the Icon view in the FileViewer closes suddenly the Workspace

### ISSUE THREAD

**Issue by pcardona34** [trunkmaster/nextspace#448]
Hi Sergii,

- Context: 
> Debian 12.8
> Linux NEXTPI 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux

- Behaviour:
After menu: "Workspace / View / Icon", and then selecting a new context on the shelf, then The Workspace self closes...

- Maybe usefull console messages:
> 2024-12-23 23:39:58.126 Workspace[1778:9b63b040] CoreFoundation: loading CFNetwork at path: /usr/lib/libCFNetwork.so
> 2024-12-23 23:39:58.126 Workspace[1778:9b63b040] CoreFoundation: failed to dynamically link symbol _CFSocketStreamCreatePair
> 2024-12-23 23:39:58.126 Workspace[1778:9b63b040] CoreFoundation: failed to dynamically link symbol _CFErrorCreateWithStreamError
> 2024-12-23 23:39:58.126 Workspace[1778:9b63b040] CoreFoundation: failed to dynamically link symbol _CFStreamErrorFromCFError

**Comment by trunkmaster** [comment]
Hi Patrick,

Please specify more info:
- how did you install NEXTSPACE?
- what directory you are in before changing to Icon view?
- what directory/file from Shelf you are selecting before crash?

P.S.: console messages takes me to the thought that you have some non-standart setup. For example, CFNetwork location set by Login.app and it's not `/usr/lib` - do you use Login.app or run Workspace through .xinitrc?

**Comment by pcardona34** [comment]
Hi Sergii,
This issue is actual. Tested on Debian 12, aarch64.
Resolution: 1680x1050 @60Hz.

### How to reproduce:


1) Select `/Applications` folder.
2) Change View to Icon.
3) Click on the `$HOME` icon on the Shelf.
Crash.

At the nextI login, I can see  a 'Segmentation fault' in the log from the previous crash.

**Comment by trunkmaster** [comment]
Can't reproduce it. Works for me on Debian 12, x86-64. Could you try to get segfault point by running Workspace under GDB and paste backtrace here?

**Comment by pcardona34** [comment]
Hi Sergii,

Good news. I found a workaround, and maybe a clue: in the `Workspace Preferences`, modifying the 'Title vidth' and then setting it back to the default setting, I can now **use the Icon View without any trouble**.

Maybe a missing statement to a variable ?

P.S.: Sorry, but I need more aknowlegement to run `gdb` with the `Workspace`. I asked the community to help about this. I promise to use it as soon I will understand it.

**Comment by pcardona34** [comment]
After last update, the previous get around is no more efficient. Now, even tweaking the IconView Preferences, the changing mode view crashes.

In the 'console.log', I noted this, maybe a clue:

> double free or corruption (out)
malloc(): mismatching next->prev_size (unsorted)

**Comment by pcardona34** [comment]
Hi Sergii,

About the debug script, I needed to modify three things to make it work:

- Line 2: the path executed as root shoud be:
`/usr/bin/Xorg`

- Line 10: I removed unkown option '-c' after the 'awk' command.
- Line 11: the test shoud be done with unary operator: '-z' (is an empty string ?) to avoid an error.

```
#!/bin/sh
# /usr/bin/Xorg :0 -noreset -background none -seat seat0 -nolisten tcp -keeptty vt1

export CFNETWORK_LIBRARY_PATH="/usr/NextSpace/lib/libCFNetwork.so"

PROG_NAME="Workspace"
PROG_PATH="/usr/NextSpace/Apps/Workspace.app/Workspace"
PROG_ARGS="--GNU-Debug=DBus --GNU-Debug=dealloc"

WS_PID="`ps auxw|grep ${PROG_NAME}|grep -v grep|grep -v /bin/sh|awk '{print $2}'`"
if [ -z "$WS_PID" ];then
    echo "Starting new '${PROG_NAME}' instance..."
    export DISPLAY=:0.0
    gnustep-services start
    gdb -q --args ${PROG_PATH} ${PROG_ARGS}
    gnustep-services stop
else
    echo "Found '${PROG_NAME}' PID: ${WS_PID}"
    gdb ${PROG_PATH} ${WS_PID}
fi
```

And it works fine now under my test machines.

**Comment by trunkmaster** [comment]
@pcardona34 latest changes should fix this issue. Please check and let me know.

**Comment by trunkmaster** [comment]
> Hi Sergii,
> 
> About the debug script, I needed to modify three things to make it work:
> 
>     * Line 2: the path executed as root shoud be:
>       `/usr/bin/Xorg`

As you wish. This is just for info.

>     * Line 10: I removed unkown option '-c' after the 'awk' command.

My setup uses GNU awk and `-c` means `Run in compatibility mode.`. It's OK not to use it.

>     * Line 11: the test shoud be done with unary operator: '-z' (is an empty string ?) to avoid an error.

It's up to you. Works both ways for me.

> 
> ```
> #!/bin/sh
> # /usr/bin/Xorg :0 -noreset -background none -seat seat0 -nolisten tcp -keeptty vt1
> 
> export CFNETWORK_LIBRARY_PATH="/usr/NextSpace/lib/libCFNetwork.so"
> 
> PROG_NAME="Workspace"
> PROG_PATH="/usr/NextSpace/Apps/Workspace.app/Workspace"
> PROG_ARGS="--GNU-Debug=DBus --GNU-Debug=dealloc"
> 
> WS_PID="`ps auxw|grep ${PROG_NAME}|grep -v grep|grep -v /bin/sh|awk '{print $2}'`"
> if [ -z "$WS_PID" ];then
>     echo "Starting new '${PROG_NAME}' instance..."
>     export DISPLAY=:0.0
>     gnustep-services start
>     gdb -q --args ${PROG_PATH} ${PROG_ARGS}
>     gnustep-services stop
> else
>     echo "Found '${PROG_NAME}' PID: ${WS_PID}"
>     gdb ${PROG_PATH} ${WS_PID}
> fi
> ```
> 
> And it works fine now under my test machines.

**Comment by trunkmaster** [comment]
@pcardona34 latest changes should fix this issue with Icon Viewer. Please check and let me know.

**Comment by pcardona34** [comment]
Not fixed under debian 12.10 aarch64. I got a large BT within gdb, but I don't know how to save it to a file. Is any key word to look for ?

**Comment by trunkmaster** [comment]
Can you just copy and paste here?

**Comment by pcardona34** [comment]
This the BT...

[BT_GDB_Workspace_IconView.txt](https://github.com/user-attachments/files/19276162/BT_GDB_Workspace_IconView.txt)

**Comment by trunkmaster** [comment]
Great, thanks! It seems that reason of crash is setting path icon lable. Could you please specify what path have you selected? Does this happen on other paths?

**Comment by pcardona34** [comment]
- On the real arm64, it ever crashes just after selecting the menu IconView item.
- On the VM arm64, it happens after a few changing... The last selected Icon on the shelf was the root FileSystem (computer Icon) named there 'debian12arm64'.
P.S.: the name of this root changes on my different test machines: elsewhere, it could be named 'pi400next', etc.

**Comment by pcardona34** [comment]
Oh! I just clicked twice on the 'SOURCES' folder (path: `$HOME/SOURCES`) and it crashes immediately...

**Comment by trunkmaster** [comment]
Where did you clicked twice: Shelf, Path View, Icon View? Double-click opens new window, BTW...

**Comment by pcardona34** [comment]
It is very difficult to follow, because the same last action can produce or not the issue. There are some scenarios:

1. New session
2. Switching to IconView from menu 'View/Icon': can immediately produce the issue 'Session finished with error' or not.
3. If not happens at step 2, these steps often result in the issue :

- Click on Home in the _Shelf_, then on the RootFileSystem (computer Icon) in the _PathView_.
- Click on Home in the _Shelf_, then 2xclick on a Folder in the _IconView_.

![Image](https://github.com/user-attachments/assets/d75f0688-9854-42e0-91ad-e302fcc0104e)

P.S.: I tried to change the width in the Preferences of IconView, but this was not helping.

**Comment by trunkmaster** [comment]
I've tried dozens of times on different setups with Fedora 41: VM on x86, x86 hardware, VM on ARM (M2). Can't reproduce it.

**Comment by armm77** [comment]
I validated it on Debian and it can replicate the error reported by @pcardona34, it remains to be tested in Ubuntu.

**Comment by trunkmaster** [comment]
Confirmed on Ubuntu 22.04 x86_64. I'll try to find a problem...

**Comment by trunkmaster** [comment]
Debian 12.10 on x86_64 (VM) works without a crash.

**Comment by pcardona34** [comment]
Not fixed under x86_64.

Just got again the issue (same scenarios as above) under Debian 12.10  x86_64 VM Guest, with Display Spice (without OpenGL nor 3D accel)
Resolution: 1024x768_60Hz

Hypervisor Details:
Hypervisor: KVM
Arch: x86_64
Emulator: /usr/bin/qemu-system-x86_64
Chipset: Q35
Firmware: BIOS

(Host:  MacBookPro6 Intel i5, Ubuntu 22.04 LTS, resolution: 1440x900)

**Comment by trunkmaster** [comment]
Good news: it seems I've found the place in code that may be a cause random crashes (shortening icon label strings and `...` addition). I need to find out why it leads to such misbehaviour. 
Bad news: code looks good. :(

**Comment by pcardona34** [comment]
Maybe this shortening icon label issue already happened in the History of Workspaces like development ? Particularly, maybe people who worked on GWorkspace in the past could help ?

**Comment by trunkmaster** [comment]
I've found and fixed cause of a problem. See latest commit. You need to reinstall libs-back: run `7_build_libs-back.sh` script.

**Comment by pcardona34** [comment]
Sergii, I do not know if there are still other problems to check, but I can say that this update seems to fix 99% of the issue. I tried many scenarios to stress the IconView and I found only one, but I could not then reproduce it.

**Comment by trunkmaster** [comment]
Closing this?

**Comment by pcardona34** [comment]
Of course, that's done.
